-- Виконати вказаний скрипт для створення тестового середовища
-- Перевірено на ORACLE 12 DATABASE

 -- DROP table EMPLOYEES

 DROP TABLE EMPLOYEES;
 
 -- DROP table DEPARTMENTS
 
 DROP TABLE DEPARTMENTS;
 
 -- CREATE table DEPARTMENTS
 
  CREATE TABLE DEPARTMENTS
  (	 
    DEPARTMENTID  NUMBER(10,0) NOT NULL, 
	  NAME  VARCHAR2(100) NOT NULL, 
	  CONSTRAINT  DEPARTMENTS_PK  PRIMARY KEY ( DEPARTMENTID )
  );
  
 -- CREATE table EMPLOYEES
 
 CREATE TABLE EMPLOYEES  
  ( 
    EMPLOYEEID  NUMBER(38,0) NOT NULL  , 
	  DEPARTMENTID  NUMBER(10,0) NOT NULL  , 
	  BOSSID  NUMBER(38,0), 
	  NAME VARCHAR2(100) NOT NULL  , 
	  SALARY NUMBER(24,2) NOT NULL  , 
    CONSTRAINT EMPLOYEES_PK PRIMARY KEY (EMPLOYEEID),
    CONSTRAINT FK_EMPLOYEES_DEPARTMENTID FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENTS (DEPARTMENTID)
  ) ;

-- INSERTING testing data into DEPARTMENTS

Insert into  DEPARTMENTS (DEPARTMENTID,NAME) values ('1','ACCOUNT');
Insert into  DEPARTMENTS (DEPARTMENTID,NAME) values ('2','FINANCE');
Insert into  DEPARTMENTS (DEPARTMENTID,NAME) values ('3','IT');
Insert into  DEPARTMENTS (DEPARTMENTID,NAME) values ('4','CREDIT');
Insert into  DEPARTMENTS (DEPARTMENTID,NAME) values ('5','TESTING');
Insert into  DEPARTMENTS (DEPARTMENTID,NAME) values ('6','CORPORATE');

commit;
   
-- INSERTING testing data into EMPLOYEES
  
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('1','1','4','Valentin','525,5');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('2','1',null,'Sergey','740');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('3','1','4','Ivan','450');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('4','1','4','Vadim','1000');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('5','1','4','Victor','350');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('6','1','4','Alex','630');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('7','1','4','Artur','200');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('8','2','10','Valentin_2','400,5');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('9','2','10','Sergey_2','450');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('10','2','10','Ivan_2','650');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('11','2','10','Vadim_2','280');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('12','2','10','Victor_2','720');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('13','2','10','Alex_2','360');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('14','2','10','Artur_2','1000');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('15','3','21','Valentin_3','520');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('16','3','21','Sergey_3','400');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('17','3','21','Ivan_3','640');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('18','3','4','Vadim_3','470');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('19','3','21','Victor_3','620');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('20','3','21','Alex_3','820');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('21','3','21','Artur_3','500');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('22','4','22','Valentin_4','450');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('23','4','22','Sergey_4','380');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('24','4','22','Ivan_4','250');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('25','4','22','Vadim_4','900');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('26','4','22','Victor_4','360');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('27','4','22','Alex_4','720');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('28','4','22','Artur_4','370');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('29','5','29','Valentin_5','700');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('30','5','29','Sergey_5','520');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('31','6',null,'Valentin_6','320');
Insert into  EMPLOYEES (EMPLOYEEID,DEPARTMENTID,BOSSID,NAME,SALARY) values ('32','6',null,'Sergey_6','450');

commit;

 -- CREATE FOREIGN KEY for field BOSSID in table EMPLOYEES 

 ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMPLOYEES_BOSSID FOREIGN KEY (BOSSID) REFERENCES EMPLOYEES (EMPLOYEEID);

 